config/routes.rb
Rails.application.routes.draw do
  #resources :products
  get 'product/index'

  get 'product/new'

  post 'product/new', to: 'product#create', as: 'product_create'

  get '/product/:id/edit', to: 'product#edit', as: 'product_edit'

  post '/product/:id/edit', to: 'product#update', as: 'product_update'

  root 'product#index'

  get "*path" => redirect("/")
  post "*path" => redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
require 'date'
class Product < ApplicationRecord
  validates :product_type, :name, :description, :presence => {:message => "empty value found"}
  validates :product_status, :price, :presence => true, :numericality => { :greater_than_or_equal_to => 0 }
  #validate :is_inward_date_valid

  def is_inward_date_valid
    errors.add(:inward_date, 'must be a valid date') if ((Date.parse(:inward_date) rescue ArgumentError) == ArgumentError)
  end
  
  def price_sum(type)
    Product.where(:product_type => type).sum(&:price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
    render 'record_not_found'
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @products = ProductDecorator.decorate_collection(Product.all)
  end

  def new
    type = params[:product_type]
    product = Product.new(:product_type => type)
    @product = ProductDecorator.new(product)
  end

  def create
    product = Product.new(product_params)
    product.product_status = 1 if product.product_status && product.product_status != 0
 
    if product.save
      redirect_to product_index_path
    else
      @product = ProductDecorator.new(product)
      render 'new'
    end
  end

  def edit
    product = Product.find(params[:id])
    @product = ProductDecorator.new(product)
  end

  def update
    product = Product.find(params[:id])
 
    if product.update(product_params)
      redirect_to product_index_path
    else
      @product = ProductDecorator.new(product)
      render 'edit'
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :inward_date, :product_status, :product_type, :price, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageProduct</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/product/edit.html.erb
<div> Edit Product </div>
<%= form_for :product, url: product_update_path do |p| %>
 
  <%= @product.any_errors %>
  <%= p.hidden_field :product_type, :value => @product.product_type %>
  <p>
    <%= p.label :name %><br>
    <%= p.text_field :name %>
  </p>
 
  <p>
    <%= p.label :description %><br>
    <%= p.text_area :description %>
  </p>

  <p>
    <%= p.label :price %><br>
    <%= p.text_field :price %>
  </p>

  <% if @product.product_type == 'Pen' %>
    <p>
      <%= p.label :color %><br>
      <%= p.text_area :color %>
    </p>
  <% end %>

  <p>
    <%= p.label :product_status %><br>
    <%= p.label :product_status, "Enabled", :value => 1  %>
    <%= p.radio_button :product_status, 1 %><br>
    <%= p.label :product_status, "Disabled", :value => 0 %>
    <%= p.radio_button :product_status, 0 %>
  </p>

  <p>
    <%= p.label :inward_date %><br>
    <%= p.text_field :inward_date, "data-provide" => 'datepicker' %>
  </p>
 
  <p>
    <%= p.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', product_index_path %>

<script type="text/javascript">
  $.fn.datepicker.defaults.format = "dd-mm-yyyy";
  $(document).ready(function(){
    $('.datepicker').datepicker({
      autoclose:true,
      format: "dd-mm-yyyy"
    });
  });
</script>

app/views/product/index.html.erb
<h1>Product</h1>
<span><%= link_to 'New Pen', product_new_path(:product_type => "Pen") %></span>
<span><%= link_to 'New Notebook', product_new_path(:product_type => "Notebook") %></span>
<% if @products.length == 0 %>
  <p>Currently there are no products. Please start by creating few products.</p>
<% else %>
  <p>Following is the list of all product</p>
  <table class="table">
    <thead>
      <tr>
        <th>Type</th>
        <th>Name</th>
        <th>Price</th>
        <th>Color</th>
        <th>Description</th>
        <th>Inward Date</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |p| %>
        <tr class="active">
          <td><%= p.product_type %></td>
          <td><%= p.name %></td>
          <td><%= p.price %></td>
          <td><%= p.colour %></td>
          <td><%= p.description %></td>
          <td><%= p.inward_date %></td>
          <td><%= p.is_available %></td>
          <td><%= link_to 'Edit', product_edit_path(p) %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
<%end%>

app/views/product/new.html.erb
<div> Add New Product </div>
<%= form_for :product, url: product_create_path do |p| %>
 
  <%= @product.any_errors %>
  <%= p.hidden_field :product_type, :value => @product.product_type %>
  <p>
    <%= p.label :name %><br>
    <%= p.text_field :name %>
  </p>
 
  <p>
    <%= p.label :description %><br>
    <%= p.text_area :description %>
  </p>

  <p>
    <%= p.label :price %><br>
    <%= p.text_field :price %>
  </p>

  <% if @product.product_type == 'Pen' %>
    <p>
      <%= p.label :color %><br>
      <%= p.text_area :color %>
    </p>
  <% end %>

  <p>
    <%= p.label :product_status %><br>
    <%= p.label :product_status, "Enabled", :value => 1  %>
    <%= p.radio_button :product_status, 1 %><br>
    <%= p.label :product_status, "Disabled", :value => 0 %>
    <%= p.radio_button :product_status, 0 %>
  </p>

  <p>
    <%= p.label :inward_date %><br>
    <%= p.text_field :inward_date, "data-provide" => 'datepicker' %>
  </p>
 
  <p>
    <%= p.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', product_index_path %>

<script type="text/javascript">
  $.fn.datepicker.defaults.format = "dd-mm-yyyy";
  $(document).ready(function(){
    $('.datepicker').datepicker({
      autoclose:true,
      format: "dd-mm-yyyy"
    });
  });
</script>

app/views/product/record_not_found.html.erb
<h2> Product you are searching is not found.</h2>
<%= link_to 'Show All Products', product_index_path %>

app/views/product/update.html.erb
<h1>Product#update</h1>
<p>Find me in app/views/product/update.html.erb</p>